language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      env: FLAGS="--no-default-features"
    - rust: nightly
    - rust: nightly
      env: FLAGS="-Z minimal-versions"
script:
  - cargo build -v $FLAGS
  - cargo doc -v $FLAGS
